use treeohealthdb;
SET FOREIGN_KEY_CHECKS=0;
drop table apptarchive_apptarchive;
drop table apptarchive_notes;
drop table auth_group;
drop table auth_group_permissions;
drop table auth_permission;
drop table blogsys_postq;
drop table django_content_type;
drop table django_migrations;
drop table django_session;
drop table doctornotes_notesobj;
drop table messaging_message;
drop table patient_log_patientlog;
drop table reqappt_appttable;
drop table upload_download_uploaded_file;
drop table users_acc_admin;
drop table users_acc_patient;
drop table users_acc_provider;
drop table users_acc_user;
drop table users_acc_user_groups;
drop table users_acc_user_user_permissions;
SET FOREIGN_KEY_CHECKS=1;